In [2]:
import numpy as np

numpy is used for numerical computing 

key feature of numpy is N-dimensional array or ndarray
it is fast flexible container for large dataset


In [3]:
data=np.array([[1,2,3],[5,6,7]])

In [4]:
data # this shows the array

array([[1, 2, 3],
       [5, 6, 7]])

In [5]:
data*7

array([[ 7, 14, 21],
       [35, 42, 49]])

In [6]:
data+data

array([[ 2,  4,  6],
       [10, 12, 14]])

In [7]:
data.shape


(2, 3)

In [8]:
data.dtype

dtype('int64')

array is created using array function, it accepts any sequence like object

In [9]:
data1=[2,4,6,8,10]

In [10]:
arr1=np.array(data1)

In [11]:
arr1

array([ 2,  4,  6,  8, 10])

In [12]:
arr1.dtype
arr1.shape

(5,)

In [14]:
data2=[[1,2,3,4,5],[2,4,6,8,10]]

In [15]:
arr2=np.array(data2)

In [16]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [ ]:
arr2.ndim # shows the dimension

2

In [18]:
arr2.shape

(2, 5)

In [19]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr2.dtype

dtype('int64')

you can eplicitly convert one data type to another

In [27]:
float_arr=arr2.astype(np.float64)
float_arr

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  4.,  6.,  8., 10.]])

In [ ]:
float_arr.dtype

dtype('float64')

you can also use another array's dtype attribut

In [29]:
one_array=np.array([1,2,3,4,5], dtype=np.int64)
another_array=np.array([2.0,3.1,4.2,5.3,7.6], dtype=np.float64)

one_array.astype(another_array.dtype)

array([1., 2., 3., 4., 5.])

In [30]:
arr2*arr2

array([[  1,   4,   9,  16,  25],
       [  4,  16,  36,  64, 100]])

In [31]:
arr2-arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
1/arr2

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.25      , 0.16666667, 0.125     , 0.1       ]])

comparison between arrays of same size yield boolean arrays

In [34]:
arr3=np.array([[3,4,5,6,7],[1,2,3,4,5]])

In [35]:
arr2>arr3

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

Basic indexing and slicing


one dimensional array are simple, on the surface they act as python list

In [36]:
arr1

array([ 2,  4,  6,  8, 10])

In [37]:
arr1[3]

np.int64(8)

In [38]:
arr1[0:3]

array([2, 4, 6])

In [41]:
arr1[2:4]=8

In [42]:
arr1

array([ 2,  4,  8,  8, 10])

array slices are viewed on the original array, data will not be copied, it directly affects the original array

In [45]:
arr1_slice=arr1[2:4]
arr1_slice

array([8, 8])

when i change the value n arr1_slice the value will also change in the orginal array

In [47]:
arr1_slice[0]=9# here i have change the 8 to 9
arr1_slice
arr1

array([ 2,  4,  9,  8, 10])

In [48]:
arr1_slice[:]=67
arr1

array([ 2,  4, 67, 67, 10])

in higher dimension, elements at each index are no longer scalars but rather one dimensional arrays

In [1]:
arr2d=([[1,2,3],[2,2,2],[4,5,6]])
arr2d[2]

[4, 5, 6]

In [5]:
#individual element can be accessed as
arr2d[0][2]


3

in multidimensional array, if you omit later indices,
the returned object will be a lower dimensional ndarray


In [11]:
a2=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
a2.shape

(2, 2, 3)

In [17]:
a2[1]

array([[3, 3, 3],
       [4, 4, 4]])

In [13]:
a2[0][1]

array([2, 2, 2])

In [16]:
a2[0][1][2]

np.int64(2)

In [18]:
a2[1]=33

In [19]:
a2

array([[[ 1,  1,  1],
        [ 2,  2,  2]],

       [[33, 33, 33],
        [33, 33, 33]]])

In [20]:
a2[0,1]

array([2, 2, 2])

this above is same as

In [21]:
x=a2[0]

In [22]:
x

array([[1, 1, 1],
       [2, 2, 2]])

In [24]:
x[1]

array([2, 2, 2])

mulit dimensional array slicing, you can pass mulitple slices

In [25]:
a2

array([[[ 1,  1,  1],
        [ 2,  2,  2]],

       [[33, 33, 33],
        [33, 33, 33]]])

In [26]:
a2[:2]

array([[[ 1,  1,  1],
        [ 2,  2,  2]],

       [[33, 33, 33],
        [33, 33, 33]]])

In [27]:
a2[:1]

array([[[1, 1, 1],
        [2, 2, 2]]])

In [29]:
a2[:1, :1]

array([[[1, 1, 1]]])

In [30]:
a2[:1,:1,:1]

array([[[1]]])

you can also mix indexes and slice

In [31]:
a2[1,:1]

array([[33, 33, 33]])

In [32]:
a2[:1, 0]

array([[1, 1, 1]])

fancy indexing---> indexing using integer arrays

In [33]:
aaa=np.zeros((6,3))

In [36]:
for i in range(6):
    aaa[i]=i

In [37]:
aaa

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])

to select a subset of the rows in particular order, you can pass a list or ndarray of integers specifying the desired order

In [38]:
aaa[[0,2,4]]

array([[0., 0., 0.],
       [2., 2., 2.],
       [4., 4., 4.]])

In [40]:
aaa[[-1,-2,-4]]

array([[5., 5., 5.],
       [4., 4., 4.],
       [2., 2., 2.]])

if we pass mulitple index arrays then we will get one dimensional array of elements corresponding to each tuple of indices

In [41]:
aaa[[0,2,4],[0,1,2]]

array([0., 2., 4.])

transposing arrays and swaping axes

In [4]:
abc=np.arange(9).reshape((3,3))
abc

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
abc.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

two ways for matrix multiplication

In [ ]:
np.dot(abc, abc.T)# one way

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [ ]:
abc @ abc.T #another way

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

trasnposing with .t is special case of swapaxes

In [9]:
abc.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [10]:
abc.swapaxes(1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [11]:
abcd=np.arange(12).reshape((3,4))
abcd

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
abcd.swapaxes(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [14]:
rng=np.random.default_rng(seed=1234)
data=rng.standard_normal((2,3))

In [14]:
type(rng)

numpy.random._generator.Generator

universal functions
or ufunc

In [15]:
dd=np.arange(5)

In [16]:
dd

array([0, 1, 2, 3, 4])

In [17]:
np.sqrt(dd)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [18]:
np.exp(dd)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

np.sqrt() and np.exp() are universal functions that perfoms element wise operations, they are unary ufuncs

below are binary ufuncs

In [19]:
f=rng.standard_normal(4)
g=rng.standard_normal(4)

In [20]:
f

array([-1.47882336,  0.94547297, -1.66613546,  0.34374458])

In [21]:
g

array([-0.51244371,  1.32375896, -0.86028019,  0.5194932 ])

In [23]:
np.maximum(f,g)

array([-0.51244371,  1.32375896, -0.86028019,  0.5194932 ])

In [24]:
np.add(f,g)

array([-1.99126707,  2.26923193, -2.52641565,  0.86323778])

array oriented programming with arrays

numpy.meshgrid() takes two one-dimensional arrays and produce two two-dimensional  matrices corresponding to all pairs of (x,y) in the two arrays

In [ ]:
points=np.arange(-5,5,1)# 10 equally spaced points
xs,ys=np.meshgrid(points, points)

In [4]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [5]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [6]:
d=np.sqrt(xs**2 + ys**2)

In [7]:
d

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

expressing conditional logic as array opterations

In [8]:
x=np.array([1,2,3,4,5])
y=np.array([2,4,6,8,10])
condition=np.array([True,False,True,True,False])

now i want to take value from x if condition is true otherwise take value from y

In [ ]:
result=[(x if c else y)
        for x,y,c in zip(x,y,condition)]


In [13]:
result

[np.int64(1), np.int64(4), np.int64(3), np.int64(4), np.int64(10)]

above code has multiple problem, first it will not be very fast for large arrays, second it will not work with multidimensional arrays.


In [10]:
#numpy.where() can be used to solve the above issue
result=np.where(condition,x,y)

In [11]:
result

array([ 1,  4,  3,  4, 10])


### when to use numpy.where()?
when you want to produce new arrays of value based on another array

In [19]:
h=rng.standard_normal((3,3))

In [20]:
h

array([[-2.15913901,  0.43473395,  1.73328932],
       [ 0.52013416, -1.00216579,  0.26834554],
       [ 0.7671747 ,  1.19127203, -1.15741081]])

In [21]:
h>0

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [22]:
np.where(h>0,6,7)

array([[7, 6, 6],
       [6, 7, 6],
       [6, 6, 7]])

In [23]:
np.where(h>0,6,h)

array([[-2.15913901,  6.        ,  6.        ],
       [ 6.        , -1.00216579,  6.        ],
       [ 6.        ,  6.        , -1.15741081]])

mathematical and statistical methods

when you use numpyfunction you have to pass array you want to aggregate as first argument

In [24]:
h.mean()

np.float64(0.0662482312760338)

In [25]:
h.sum()

np.float64(0.5962340814843041)

In [27]:
#np.sum() # this will cause error, since there is no argument
np.sum(h)

np.float64(0.5962340814843041)

In [28]:
h.mean(axis=1)# compute mean across the columns

array([ 0.00296142, -0.0712287 ,  0.26701197])

In [29]:
h.sum(axis=0)# compute sum down the rows

array([-0.87183015,  0.62384018,  0.84422405])

methods for boolean arrays

In [30]:
bools=np.array([True,False,True,False,False])

In [31]:
bools.any()#checks if there is at least one value True

np.True_

In [32]:
bools.all()#checks if all the values are True

np.False_

sorting


In [34]:
h.sort()
h

array([[-2.15913901,  0.43473395,  1.73328932],
       [-1.00216579,  0.26834554,  0.52013416],
       [-1.15741081,  0.7671747 ,  1.19127203]])

you can sort each 1d section of values in multidimensional array in place along an axis by passing the axis number to sort

In [35]:
h.sort(axis=1)#sort across each row

In [36]:
h

array([[-2.15913901,  0.43473395,  1.73328932],
       [-1.00216579,  0.26834554,  0.52013416],
       [-1.15741081,  0.7671747 ,  1.19127203]])

In [37]:
h.sort(axis=0)#sort with each column
h

array([[-2.15913901,  0.26834554,  0.52013416],
       [-1.15741081,  0.43473395,  1.19127203],
       [-1.00216579,  0.7671747 ,  1.73328932]])

top level numpy.sort() returns the sorted copy of an array instead of modifying array in place

In [40]:
h1=np.array([1,22,3,56,7,11])
sorted_h1=np.sort(h1)

In [41]:
sorted_h1

array([ 1,  3,  7, 11, 22, 56])