In [9]:
import numpy as np

numpy is used for numerical computing 

key feature of numpy is N-dimensional array or ndarray
it is fast flexible container for large dataset


In [3]:
data=np.array([[1,2,3],[5,6,7]])

In [4]:
data # this shows the array

array([[1, 2, 3],
       [5, 6, 7]])

In [5]:
data*7

array([[ 7, 14, 21],
       [35, 42, 49]])

In [6]:
data+data

array([[ 2,  4,  6],
       [10, 12, 14]])

In [7]:
data.shape


(2, 3)

In [8]:
data.dtype

dtype('int64')

array is created using array function, it accepts any sequence like object

In [9]:
data1=[2,4,6,8,10]

In [10]:
arr1=np.array(data1)

In [11]:
arr1

array([ 2,  4,  6,  8, 10])

In [12]:
arr1.dtype
arr1.shape

(5,)

In [14]:
data2=[[1,2,3,4,5],[2,4,6,8,10]]

In [15]:
arr2=np.array(data2)

In [16]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [ ]:
arr2.ndim # shows the dimension

2

In [18]:
arr2.shape

(2, 5)

In [19]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr2.dtype

dtype('int64')

you can eplicitly convert one data type to another

In [27]:
float_arr=arr2.astype(np.float64)
float_arr

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  4.,  6.,  8., 10.]])

In [ ]:
float_arr.dtype

dtype('float64')

you can also use another array's dtype attribut

In [29]:
one_array=np.array([1,2,3,4,5], dtype=np.int64)
another_array=np.array([2.0,3.1,4.2,5.3,7.6], dtype=np.float64)

one_array.astype(another_array.dtype)

array([1., 2., 3., 4., 5.])

In [30]:
arr2*arr2

array([[  1,   4,   9,  16,  25],
       [  4,  16,  36,  64, 100]])

In [31]:
arr2-arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
1/arr2

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.25      , 0.16666667, 0.125     , 0.1       ]])

comparison between arrays of same size yield boolean arrays

In [34]:
arr3=np.array([[3,4,5,6,7],[1,2,3,4,5]])

In [35]:
arr2>arr3

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

Basic indexing and slicing


one dimensional array are simple, on the surface they act as python list

In [36]:
arr1

array([ 2,  4,  6,  8, 10])

In [37]:
arr1[3]

np.int64(8)

In [38]:
arr1[0:3]

array([2, 4, 6])

In [41]:
arr1[2:4]=8

In [42]:
arr1

array([ 2,  4,  8,  8, 10])

array slices are viewed on the original array, data will not be copied, it directly affects the original array

In [45]:
arr1_slice=arr1[2:4]
arr1_slice

array([8, 8])

when i change the value n arr1_slice the value will also change in the orginal array

In [47]:
arr1_slice[0]=9# here i have change the 8 to 9
arr1_slice
arr1

array([ 2,  4,  9,  8, 10])

In [48]:
arr1_slice[:]=67
arr1

array([ 2,  4, 67, 67, 10])

in higher dimension, elements at each index are no longer scalars but rather one dimensional arrays

In [1]:
arr2d=([[1,2,3],[2,2,2],[4,5,6]])
arr2d[2]

[4, 5, 6]

In [5]:
#individual element can be accessed as
arr2d[0][2]


3

in multidimensional array, if you omit later indices,
the returned object will be a lower dimensional ndarray


In [11]:
a2=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
a2.shape

(2, 2, 3)

In [17]:
a2[1]

array([[3, 3, 3],
       [4, 4, 4]])

In [13]:
a2[0][1]

array([2, 2, 2])

In [16]:
a2[0][1][2]

np.int64(2)

In [18]:
a2[1]=33

In [19]:
a2

array([[[ 1,  1,  1],
        [ 2,  2,  2]],

       [[33, 33, 33],
        [33, 33, 33]]])

In [20]:
a2[0,1]

array([2, 2, 2])

this above is same as

In [21]:
x=a2[0]

In [22]:
x

array([[1, 1, 1],
       [2, 2, 2]])

In [24]:
x[1]

array([2, 2, 2])

mulit dimensional array slicing, you can pass mulitple slices

In [25]:
a2

array([[[ 1,  1,  1],
        [ 2,  2,  2]],

       [[33, 33, 33],
        [33, 33, 33]]])

In [26]:
a2[:2]

array([[[ 1,  1,  1],
        [ 2,  2,  2]],

       [[33, 33, 33],
        [33, 33, 33]]])

In [27]:
a2[:1]

array([[[1, 1, 1],
        [2, 2, 2]]])

In [29]:
a2[:1, :1]

array([[[1, 1, 1]]])

In [30]:
a2[:1,:1,:1]

array([[[1]]])

you can also mix indexes and slice

In [31]:
a2[1,:1]

array([[33, 33, 33]])

In [32]:
a2[:1, 0]

array([[1, 1, 1]])